[package]
name = "cryptopals"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.3"
base64 = { version = "0.22.1"}
clap = { version = "4.0", features = ["derive"] }
hex = { version = "0.4.3"}
openssl = { version = "0.10", features = ["vendored"] }
